// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgcnpektfjricftxrmnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnY25wZWt0ZmpyaWNmdHhybW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTk5MzAsImV4cCI6MjA3MjQzNTkzMH0.GUrQbWC6lo7wABkXR3AFfompXwEnpBWi0AlI1zX19Ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});